# version: 2.1
# workflows:
#   build:
#     jobs:
#       - build-erd
version: 2
jobs:
  build-erd:
    docker:
      - image: schemaspy/schemaspy:snapshot
        user: root
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: circle_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
    steps:
      - checkout
      - run:
          command: |
            apk update
            apk add openssl mariadb-client
      - run:
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: cat /root/project/mysql/TestTable.sql | mysql --defaults-extra-file=/root/project/mysql/db_access.conf circle_test
      - run: cd / && /entrypoint.sh -t mysql -host 127.0.0.1 -port 3306 -u root -db circle_test -s information_schema -hq useSSL\\=false
      - store_artifacts:
          path: /output
          destination: er
